/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculadora;

import static org.junit.Assert.*;

 

import org.junit.Test;

 

import Calculadora.App;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;

import org.junit.Before;

 

 

public class AppTest {

    private App calculadora;

    @Before
    public void setup() throws Exception {
        calculadora = new App();
    }

    @Test
    public void testaSomar() {
        App calc = new App();
        int resultado = calc.adicao(5, 3);
        assertEquals(8, resultado);
    }


    @Test
    public void testaSubtrair() {
        assertEquals("",1, calculadora.subtracao(5, 4));
    }

    @Test
    public void testaMultiplicar() {
        assertEquals("",20, calculadora.multiplicacao(5, 4));
    }

    @Test
    public void testDividir() {
        App calc = new App();
        double resultado = calc.dividir(15, 3);
        assertEquals(5, resultado, 0.001);
    }

 

    @Test
    public void testDivisaoPorZero() {
        App calc = new App();
        assertThrows(ArithmeticException.class, () -> {
            calc.dividir(10, 0);
        });
    }
}